/**
 * Seed: Clients
 * Creates realistic Brazilian client data
 */

exports.seed = async function(knex) {
  // Clear existing entries
  await knex('clients').del();

  // Helper function to generate random CPF
  function generateCPF() {
    const cpf = Math.random().toString().substr(2, 11);
    return cpf.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/, '$1.$2.$3-$4');
  }

  // Helper function to generate random CNPJ
  function generateCNPJ() {
    const cnpj = Math.random().toString().substr(2, 14);
    return cnpj.replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, '$1.$2.$3/$4-$5');
  }

  // Insert realistic client data
  await knex('clients').insert([
    // Individual clients (CPF)
    {
      id: 1,
      name: 'João Silva Santos',
      email: 'joao.santos@email.com',
      phone: '(11) 98765-4321',
      mobile: '(11) 99876-5432',
      cpf_cnpj: '123.456.789-01',
      person_type: 'individual',
      address_street: 'Rua das Flores',
      address_number: '123',
      address_complement: 'Apto 45',
      address_neighborhood: 'Jardim Europa',
      address_city: 'São Paulo',
      address_state: 'SP',
      address_zipcode: '01234-567',
      credit_limit: 5000.00,
      current_balance: 0.00,
      payment_terms: '30_days',
      status: 'active',
      category: 'Varejo',
      segment: 'Consumidor Final',
      origin: 'Site',
      notes: 'Cliente fiel, sempre pontual nos pagamentos'
    },
    {
      id: 2,
      name: 'Maria Oliveira Costa',
      email: 'maria.costa@gmail.com',
      phone: '(11) 97654-3210',
      mobile: '(11) 98765-4321',
      cpf_cnpj: '987.654.321-00',
      person_type: 'individual',
      address_street: 'Av. Paulista',
      address_number: '2000',
      address_complement: 'Bloco A',
      address_neighborhood: 'Bela Vista',
      address_city: 'São Paulo',
      address_state: 'SP',
      address_zipcode: '01310-100',
      credit_limit: 3000.00,
      current_balance: 250.00,
      payment_terms: 'cash',
      status: 'active',
      category: 'Varejo',
      segment: 'Consumidor Final',
      origin: 'Indicação',
      notes: 'Prefere pagamento à vista'
    },
    {
      id: 3,
      name: 'Pedro Henrique Almeida',
      email: 'pedro.almeida@hotmail.com',
      phone: '(21) 96543-2109',
      mobile: '(21) 97654-3210',
      cpf_cnpj: '456.789.123-45',
      person_type: 'individual',
      address_street: 'Rua Copacabana',
      address_number: '456',
      address_neighborhood: 'Copacabana',
      address_city: 'Rio de Janeiro',
      address_state: 'RJ',
      address_zipcode: '22070-011',
      credit_limit: 2000.00,
      current_balance: 0.00,
      payment_terms: '60_days',
      status: 'active',
      category: 'Varejo',
      segment: 'Consumidor Final',
      origin: 'Telefone'
    },

    // Companies (CNPJ)
    {
      id: 4,
      name: 'TechSolutions Ltda',
      company_name: 'TechSolutions Serviços de Informática Ltda',
      trade_name: 'TechSolutions',
      email: 'contato@techsolutions.com.br',
      phone: '(11) 3456-7890',
      mobile: '(11) 94567-8901',
      cpf_cnpj: '12.345.678/0001-90',
      person_type: 'company',
      state_registration: '123.456.789.012',
      municipal_registration: '987654321',
      address_street: 'Rua Tecnologia',
      address_number: '1000',
      address_complement: 'Sala 501',
      address_neighborhood: 'Vila Olímpia',
      address_city: 'São Paulo',
      address_state: 'SP',
      address_zipcode: '04551-010',
      credit_limit: 50000.00,
      current_balance: 15000.00,
      payment_terms: '30_days',
      status: 'active',
      category: 'Corporativo',
      segment: 'Tecnologia',
      origin: 'Visita',
      website: 'https://techsolutions.com.br',
      notes: 'Cliente corporativo importante, compras regulares'
    },
    {
      id: 5,
      name: 'Comercial Nordeste ME',
      company_name: 'Comercial Nordeste Microempresa',
      trade_name: 'Comercial Nordeste',
      email: 'vendas@comercialnordeste.com.br',
      phone: '(85) 3234-5678',
      mobile: '(85) 98765-4321',
      cpf_cnpj: '23.456.789/0001-01',
      person_type: 'company',
      state_registration: '234.567.890.123',
      address_street: 'Av. Beira Mar',
      address_number: '2500',
      address_neighborhood: 'Meireles',
      address_city: 'Fortaleza',
      address_state: 'CE',
      address_zipcode: '60165-121',
      credit_limit: 25000.00,
      current_balance: 5000.00,
      payment_terms: '30_days',
      status: 'active',
      category: 'Atacado',
      segment: 'Comércio',
      origin: 'Feira',
      website: 'https://comercialnordeste.com.br'
    },
    {
      id: 6,
      name: 'Indústria Mineira S.A.',
      company_name: 'Indústria Mineira de Produtos Diversos S.A.',
      trade_name: 'Indústria Mineira',
      email: 'compras@industriamineira.com.br',
      phone: '(31) 3345-6789',
      mobile: '(31) 97654-3210',
      cpf_cnpj: '34.567.890/0001-12',
      person_type: 'company',
      state_registration: '345.678.901.234',
      municipal_registration: '876543210',
      address_street: 'Rua Industrial',
      address_number: '500',
      address_neighborhood: 'Distrito Industrial',
      address_city: 'Belo Horizonte',
      address_state: 'MG',
      address_zipcode: '30112-000',
      credit_limit: 100000.00,
      current_balance: 35000.00,
      payment_terms: '60_days',
      status: 'active',
      category: 'Distribuidor',
      segment: 'Indústria',
      origin: 'Representante',
      website: 'https://industriamineira.com.br',
      notes: 'Grande cliente industrial, negocia grandes volumes'
    },
    {
      id: 7,
      name: 'Distribuidora Sul Ltda',
      company_name: 'Distribuidora Sul de Produtos Alimentícios Ltda',
      trade_name: 'Distribuidora Sul',
      email: 'pedidos@distribuidorasul.com.br',
      phone: '(51) 3456-7890',
      mobile: '(51) 98765-4321',
      cpf_cnpj: '45.678.901/0001-23',
      person_type: 'company',
      state_registration: '456.789.012.345',
      address_street: 'Av. Ipiranga',
      address_number: '1500',
      address_neighborhood: 'Azenha',
      address_city: 'Porto Alegre',
      address_state: 'RS',
      address_zipcode: '90160-093',
      credit_limit: 75000.00,
      current_balance: 12000.00,
      payment_terms: '30_days',
      status: 'active',
      category: 'Distribuidor',
      segment: 'Distribuição',
      origin: 'Site',
      website: 'https://distribuidorasul.com.br'
    },
    {
      id: 8,
      name: 'Loja Virtual 24h EPP',
      company_name: 'Loja Virtual 24 Horas Empresa de Pequeno Porte',
      trade_name: 'Loja Virtual 24h',
      email: 'atendimento@lojavirtual24h.com.br',
      phone: '(11) 4567-8901',
      mobile: '(11) 96543-2109',
      cpf_cnpj: '56.789.012/0001-34',
      person_type: 'company',
      state_registration: '567.890.123.456',
      address_street: 'Rua Comércio Eletrônico',
      address_number: '800',
      address_complement: 'Galpão 5',
      address_neighborhood: 'Alphaville',
      address_city: 'Barueri',
      address_state: 'SP',
      address_zipcode: '06454-000',
      credit_limit: 20000.00,
      current_balance: 3000.00,
      payment_terms: '30_days',
      status: 'active',
      category: 'Revendedor',
      segment: 'E-commerce',
      origin: 'Online',
      website: 'https://lojavirtual24h.com.br',
      notes: 'E-commerce em crescimento, boa perspectiva'
    },
    {
      id: 9,
      name: 'Supermercado Família Ltda',
      company_name: 'Supermercado Família Produtos Alimentícios Ltda',
      trade_name: 'Supermercado Família',
      email: 'gerencia@supermercadofamilia.com.br',
      phone: '(19) 3234-5678',
      mobile: '(19) 98765-4321',
      cpf_cnpj: '67.890.123/0001-45',
      person_type: 'company',
      state_registration: '678.901.234.567',
      address_street: 'Rua Principal',
      address_number: '1200',
      address_neighborhood: 'Centro',
      address_city: 'Campinas',
      address_state: 'SP',
      address_zipcode: '13010-111',
      credit_limit: 40000.00,
      current_balance: 8000.00,
      payment_terms: '30_days',
      status: 'active',
      category: 'Atacado',
      segment: 'Supermercado',
      origin: 'Visita',
      notes: 'Rede de supermercados local, 5 lojas'
    },
    {
      id: 10,
      name: 'Construtora Horizonte S.A.',
      company_name: 'Construtora Horizonte Empreendimentos S.A.',
      trade_name: 'Construtora Horizonte',
      email: 'compras@construtorahorizonte.com.br',
      phone: '(62) 3345-6789',
      mobile: '(62) 97654-3210',
      cpf_cnpj: '78.901.234/0001-56',
      person_type: 'company',
      state_registration: '789.012.345.678',
      municipal_registration: '765432109',
      address_street: 'Av. Construção',
      address_number: '3000',
      address_complement: 'Torre A',
      address_neighborhood: 'Setor Bueno',
      address_city: 'Goiânia',
      address_state: 'GO',
      address_zipcode: '74210-010',
      credit_limit: 200000.00,
      current_balance: 45000.00,
      payment_terms: '60_days',
      status: 'active',
      category: 'Corporativo',
      segment: 'Construção',
      origin: 'Licitação',
      website: 'https://construtorahorizonte.com.br',
      notes: 'Grande construtora, projetos de alto valor'
    }
  ]);

  console.log('✅ Clients seeded successfully');
  console.log('   - 3 individual clients (CPF)');
  console.log('   - 7 company clients (CNPJ)');
  console.log('   - Total: 10 clients');
};