/**
 * Seed: Products
 * Creates realistic Brazilian product catalog
 */

exports.seed = async function(knex) {
  // Clear existing entries
  await knex('products').del();

  // Insert realistic product data
  await knex('products').insert([
    // Electronics
    {
      id: 1,
      code: 'SMAR001',
      barcode: '7891234567890',
      description: 'Smartphone Samsung Galaxy A54 128GB',
      detailed_description: 'Smartphone Samsung Galaxy A54 5G com 128GB de armazenamento, tela de 6.4 polegadas, câmera tripla de 50MP, bateria 5000mAh',
      category: 'Eletrônicos',
      subcategory: 'Smartphones',
      brand: 'Samsung',
      model: 'Galaxy A54',
      unit: 'UN',
      cost_price: 1200.00,
      sale_price: 1599.00,
      margin_percentage: 33.25,
      markup_percentage: 24.92,
      current_stock: 25,
      minimum_stock: 5,
      maximum_stock: 100,
      reorder_point: 10,
      reorder_quantity: 20,
      weight: 0.202,
      height: 15.8,
      width: 7.67,
      length: 0.82,
      ncm_code: '85171200',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'SAMS-A54-128',
      notes: 'Produto com alta rotatividade'
    },
    {
      id: 2,
      code: 'LAPT001',
      barcode: '7891234567891',
      description: 'Notebook Lenovo IdeaPad 3i Intel Core i5',
      detailed_description: 'Notebook Lenovo IdeaPad 3i com processador Intel Core i5, 8GB RAM, SSD 256GB, tela 15.6 polegadas Full HD',
      category: 'Eletrônicos',
      subcategory: 'Laptops',
      brand: 'Lenovo',
      model: 'IdeaPad 3i',
      unit: 'UN',
      cost_price: 2800.00,
      sale_price: 3499.00,
      margin_percentage: 24.97,
      markup_percentage: 19.98,
      current_stock: 12,
      minimum_stock: 3,
      maximum_stock: 30,
      reorder_point: 5,
      reorder_quantity: 10,
      weight: 1.65,
      height: 25.0,
      width: 36.0,
      length: 2.0,
      ncm_code: '84713000',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'LNV-IP3I-I5'
    },
    {
      id: 3,
      code: 'TABL001',
      barcode: '7891234567892',
      description: 'Tablet Apple iPad 9ª Geração 64GB Wi-Fi',
      detailed_description: 'Tablet Apple iPad 9ª Geração com 64GB, tela Retina 10.2 polegadas, chip A13 Bionic, Wi-Fi',
      category: 'Eletrônicos',
      subcategory: 'Tablets',
      brand: 'Apple',
      model: 'iPad 9ª Geração',
      unit: 'UN',
      cost_price: 2200.00,
      sale_price: 2799.00,
      margin_percentage: 27.22,
      markup_percentage: 21.41,
      current_stock: 8,
      minimum_stock: 2,
      maximum_stock: 25,
      reorder_point: 4,
      reorder_quantity: 8,
      weight: 0.487,
      height: 25.06,
      width: 17.41,
      length: 0.75,
      ncm_code: '84713000',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'APL-IPD9-64'
    },
    {
      id: 4,
      code: 'TVSO001',
      barcode: '7891234567893',
      description: 'Smart TV LG 55" UHD 4K LED',
      detailed_description: 'Smart TV LG 55 polegadas UHD 4K LED com WebOS, HDR10 Pro, AI ThinQ, Wi-Fi integrado',
      category: 'Eletrônicos',
      subcategory: 'TV e Som',
      brand: 'LG',
      model: '55UP7750PSB',
      unit: 'UN',
      cost_price: 1800.00,
      sale_price: 2299.00,
      margin_percentage: 27.73,
      markup_percentage: 21.72,
      current_stock: 15,
      minimum_stock: 3,
      maximum_stock: 40,
      reorder_point: 5,
      reorder_quantity: 12,
      weight: 15.9,
      height: 71.4,
      width: 123.0,
      length: 8.6,
      ncm_code: '85287200',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'LG-55UP7750'
    },

    // Clothing
    {
      id: 5,
      code: 'CAMI001',
      barcode: '7891234567894',
      description: 'Camiseta Polo Masculina Lacoste',
      detailed_description: 'Camiseta Polo Masculina Lacoste, 100% algodão, manga curta, disponível em várias cores',
      category: 'Roupas e Acessórios',
      subcategory: 'Roupas Masculinas',
      brand: 'Lacoste',
      model: 'Polo Clássica',
      unit: 'UN',
      cost_price: 180.00,
      sale_price: 299.00,
      margin_percentage: 66.11,
      markup_percentage: 39.78,
      current_stock: 45,
      minimum_stock: 10,
      maximum_stock: 100,
      reorder_point: 20,
      reorder_quantity: 30,
      weight: 0.250,
      ncm_code: '61051000',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'LAC-POLO-M'
    },
    {
      id: 6,
      code: 'CALC001',
      barcode: '7891234567895',
      description: 'Tênis Nike Air Max 270 Masculino',
      detailed_description: 'Tênis Nike Air Max 270 Masculino, tecnologia Air Max, solado em borracha, cabedal em mesh',
      category: 'Roupas e Acessórios',
      subcategory: 'Calçados',
      brand: 'Nike',
      model: 'Air Max 270',
      unit: 'PAR',
      cost_price: 350.00,
      sale_price: 499.00,
      margin_percentage: 42.58,
      markup_percentage: 29.86,
      current_stock: 30,
      minimum_stock: 8,
      maximum_stock: 60,
      reorder_point: 15,
      reorder_quantity: 25,
      weight: 0.800,
      height: 12.0,
      width: 30.0,
      length: 20.0,
      ncm_code: '64039900',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'NIKE-AM270'
    },
    {
      id: 7,
      code: 'BOLS001',
      barcode: '7891234567896',
      description: 'Bolsa Feminina Couro Legitimo',
      detailed_description: 'Bolsa Feminina em couro legítimo, com alça transversal, compartimentos internos, acabamento premium',
      category: 'Roupas e Acessórios',
      subcategory: 'Bolsas e Carteiras',
      brand: 'Marca Própria',
      model: 'Clássica',
      unit: 'UN',
      cost_price: 120.00,
      sale_price: 199.00,
      margin_percentage: 65.83,
      markup_percentage: 39.67,
      current_stock: 20,
      minimum_stock: 5,
      maximum_stock: 50,
      reorder_point: 10,
      reorder_quantity: 15,
      weight: 0.650,
      height: 25.0,
      width: 30.0,
      length: 15.0,
      ncm_code: '42023200',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'MP-BOLSA-01'
    },

    // Home & Garden
    {
      id: 8,
      code: 'ELET001',
      barcode: '7891234567897',
      description: 'Micro-ondas Electrolux 30L Branco',
      detailed_description: 'Micro-ondas Electrolux 30 litros, 10 níveis de potência, função descongelar, painel touch',
      category: 'Casa e Jardim',
      subcategory: 'Eletrodomésticos',
      brand: 'Electrolux',
      model: 'MEF41',
      unit: 'UN',
      cost_price: 450.00,
      sale_price: 599.00,
      margin_percentage: 33.11,
      markup_percentage: 24.89,
      current_stock: 18,
      minimum_stock: 4,
      maximum_stock: 35,
      reorder_point: 8,
      reorder_quantity: 12,
      weight: 12.5,
      height: 29.0,
      width: 52.0,
      length: 43.0,
      ncm_code: '85165000',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'ELUX-MEF41'
    },
    {
      id: 9,
      code: 'MOBI001',
      barcode: '7891234567898',
      description: 'Sofá 3 Lugares Suede Cinza',
      detailed_description: 'Sofá 3 lugares em suede cinza, estrutura de madeira maciça, espuma D33, pés em madeira',
      category: 'Casa e Jardim',
      subcategory: 'Móveis',
      brand: 'Móveis Sul',
      model: 'Comfort',
      unit: 'UN',
      cost_price: 800.00,
      sale_price: 1299.00,
      margin_percentage: 62.36,
      markup_percentage: 38.44,
      current_stock: 5,
      minimum_stock: 2,
      maximum_stock: 15,
      reorder_point: 3,
      reorder_quantity: 6,
      weight: 85.0,
      height: 85.0,
      width: 190.0,
      length: 95.0,
      ncm_code: '94018000',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'MSUL-SOFA-3L'
    },

    // Sports & Leisure
    {
      id: 10,
      code: 'BIKE001',
      barcode: '7891234567899',
      description: 'Bicicleta Mountain Bike Aro 29',
      detailed_description: 'Bicicleta Mountain Bike aro 29, quadro em alumínio, 21 marchas Shimano, freio a disco',
      category: 'Esportes e Lazer',
      subcategory: 'Ciclismo',
      brand: 'Caloi',
      model: 'Explorer Sport',
      unit: 'UN',
      cost_price: 1200.00,
      sale_price: 1799.00,
      margin_percentage: 49.92,
      markup_percentage: 33.25,
      current_stock: 8,
      minimum_stock: 2,
      maximum_stock: 20,
      reorder_point: 4,
      reorder_quantity: 8,
      weight: 15.5,
      height: 110.0,
      width: 185.0,
      length: 70.0,
      ncm_code: '87120000',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'CALOI-EXP29'
    },

    // Automotive
    {
      id: 11,
      code: 'PNEU001',
      barcode: '7891234567800',
      description: 'Pneu Michelin Energy XM2 185/65R15',
      detailed_description: 'Pneu Michelin Energy XM2 185/65R15, composto de borracha especial, maior durabilidade',
      category: 'Automotivo',
      subcategory: 'Pneus',
      brand: 'Michelin',
      model: 'Energy XM2',
      unit: 'UN',
      cost_price: 280.00,
      sale_price: 399.00,
      margin_percentage: 42.52,
      markup_percentage: 29.82,
      current_stock: 24,
      minimum_stock: 8,
      maximum_stock: 60,
      reorder_point: 12,
      reorder_quantity: 20,
      weight: 8.5,
      height: 63.0,
      width: 63.0,
      length: 18.5,
      ncm_code: '40111000',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'MICH-XM2-185'
    },

    // Tools
    {
      id: 12,
      code: 'FERR001',
      barcode: '7891234567801',
      description: 'Furadeira de Impacto Bosch 650W',
      detailed_description: 'Furadeira de Impacto Bosch 650W, mandril 13mm, função martelo, velocidade variável',
      category: 'Ferramentas',
      subcategory: 'Ferramentas Elétricas',
      brand: 'Bosch',
      model: 'GSB 650 RE',
      unit: 'UN',
      cost_price: 220.00,
      sale_price: 329.00,
      margin_percentage: 49.54,
      markup_percentage: 33.18,
      current_stock: 15,
      minimum_stock: 3,
      maximum_stock: 30,
      reorder_point: 6,
      reorder_quantity: 12,
      weight: 1.8,
      height: 25.0,
      width: 35.0,
      length: 8.0,
      ncm_code: '84672990',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'BOSCH-GSB650'
    },

    // Health & Beauty
    {
      id: 13,
      code: 'COSM001',
      barcode: '7891234567802',
      description: 'Creme Hidratante Nivea Soft 200ml',
      detailed_description: 'Creme Hidratante Nivea Soft 200ml, hidratação intensa, absorção rápida, para todos os tipos de pele',
      category: 'Saúde e Beleza',
      subcategory: 'Cosméticos',
      brand: 'Nivea',
      model: 'Soft',
      unit: 'UN',
      cost_price: 12.00,
      sale_price: 19.90,
      margin_percentage: 65.83,
      markup_percentage: 39.67,
      current_stock: 80,
      minimum_stock: 20,
      maximum_stock: 200,
      reorder_point: 40,
      reorder_quantity: 60,
      weight: 0.220,
      height: 15.0,
      width: 6.0,
      length: 4.0,
      ncm_code: '33049990',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'NIVEA-SOFT-200'
    },

    // Food & Beverages
    {
      id: 14,
      code: 'ALIM001',
      barcode: '7891234567803',
      description: 'Café em Grãos Pilão Tradicional 500g',
      detailed_description: 'Café em Grãos Pilão Tradicional 500g, torra média, aroma intenso, qualidade premium',
      category: 'Alimentos e Bebidas',
      subcategory: 'Café',
      brand: 'Pilão',
      model: 'Tradicional',
      unit: 'UN',
      cost_price: 18.00,
      sale_price: 26.90,
      margin_percentage: 49.44,
      markup_percentage: 33.06,
      current_stock: 120,
      minimum_stock: 30,
      maximum_stock: 300,
      reorder_point: 60,
      reorder_quantity: 100,
      weight: 0.500,
      height: 20.0,
      width: 12.0,
      length: 8.0,
      ncm_code: '09011100',
      icms_percentage: 7.00,
      status: 'active',
      type: 'product',
      supplier_code: 'PILAO-TRAD-500'
    },

    // Office supplies
    {
      id: 15,
      code: 'ESCR001',
      barcode: '7891234567804',
      description: 'Impressora Multifuncional HP DeskJet 2774',
      detailed_description: 'Impressora Multifuncional HP DeskJet 2774, impressão colorida, Wi-Fi, scanner, copiadora',
      category: 'Escritório',
      subcategory: 'Impressoras',
      brand: 'HP',
      model: 'DeskJet 2774',
      unit: 'UN',
      cost_price: 380.00,
      sale_price: 549.00,
      margin_percentage: 44.53,
      markup_percentage: 30.79,
      current_stock: 12,
      minimum_stock: 3,
      maximum_stock: 25,
      reorder_point: 5,
      reorder_quantity: 10,
      weight: 5.42,
      height: 15.5,
      width: 43.1,
      length: 50.6,
      ncm_code: '84433210',
      icms_percentage: 18.00,
      status: 'active',
      type: 'product',
      supplier_code: 'HP-DJ2774'
    }
  ]);

  console.log('✅ Products seeded successfully');
  console.log('   - 15 products across multiple categories');
  console.log('   - Electronics: 4 products');
  console.log('   - Clothing: 3 products');
  console.log('   - Home & Garden: 2 products');
  console.log('   - Sports, Automotive, Tools, Health, Food, Office: 1 each');
};