/**
 * Seed: Suppliers
 * Creates realistic Brazilian supplier data
 */

exports.seed = async function(knex) {
  // Clear existing entries
  await knex('suppliers').del();

  // Insert realistic supplier data
  await knex('suppliers').insert([
    {
      id: 1,
      name: 'Distribuidora TechBrasil Ltda',
      cnpj: '11.222.333/0001-44',
      company_name: 'Distribuidora TechBrasil Eletrônicos Ltda',
      trade_name: 'TechBrasil',
      state_registration: '111.222.333.444',
      municipal_registration: '123456789',
      contact_person: 'Carlos Eduardo Silva',
      email: 'vendas@techbrasil.com.br',
      phone: '(11) 4567-8901',
      mobile: '(11) 98765-4321',
      fax: '(11) 4567-8900',
      website: 'https://techbrasil.com.br',
      address_street: 'Rua Tecnologia',
      address_number: '2500',
      address_complement: 'Galpão A',
      address_neighborhood: 'Distrito Industrial',
      address_city: 'São Paulo',
      address_state: 'SP',
      address_zipcode: '08500-000',
      payment_terms: '30_days',
      credit_limit: 500000.00,
      current_balance: 85000.00,
      discount_percentage: 3.00,
      delivery_days: 5,
      status: 'active',
      category: 'Distribuidor',
      segment: 'Eletrônicos',
      rating: 5,
      bank_name: 'Banco do Brasil',
      bank_agency: '1234',
      bank_account: '12345-6',
      pix_key: 'vendas@techbrasil.com.br',
      notes: 'Fornecedor premium de eletrônicos, atende todo Brasil',
      contacts: JSON.stringify([
        { name: 'Maria Santos', role: 'Gerente Comercial', phone: '(11) 98765-4322', email: 'maria@techbrasil.com.br' },
        { name: 'João Pedro', role: 'Vendedor', phone: '(11) 98765-4323', email: 'joao@techbrasil.com.br' }
      ]),
      products_supplied: JSON.stringify(['Smartphones', 'Tablets', 'Laptops', 'Acessórios Eletrônicos'])
    },
    {
      id: 2,
      name: 'Confecções Nordeste S.A.',
      cnpj: '22.333.444/0001-55',
      company_name: 'Confecções Nordeste Têxtil S.A.',
      trade_name: 'Confecções Nordeste',
      state_registration: '222.333.444.555',
      municipal_registration: '234567890',
      contact_person: 'Ana Paula Oliveira',
      email: 'comercial@confeccoesnordeste.com.br',
      phone: '(85) 3456-7890',
      mobile: '(85) 99876-5432',
      website: 'https://confeccoesnordeste.com.br',
      address_street: 'Av. Industrial',
      address_number: '1800',
      address_neighborhood: 'Maracanaú',
      address_city: 'Maracanaú',
      address_state: 'CE',
      address_zipcode: '61939-140',
      payment_terms: '30_days',
      credit_limit: 300000.00,
      current_balance: 45000.00,
      discount_percentage: 5.00,
      delivery_days: 10,
      status: 'active',
      category: 'Fabricante',
      segment: 'Têxtil',
      rating: 4,
      bank_name: 'Banco Nordeste',
      bank_agency: '2345',
      bank_account: '23456-7',
      pix_key: '22.333.444/0001-55',
      notes: 'Fabricante de roupas e acessórios, foco no mercado nordestino',
      contacts: JSON.stringify([
        { name: 'Roberto Lima', role: 'Diretor Comercial', phone: '(85) 99876-5433', email: 'roberto@confeccoesnordeste.com.br' },
        { name: 'Carla Mendes', role: 'Supervisora de Vendas', phone: '(85) 99876-5434', email: 'carla@confeccoesnordeste.com.br' }
      ]),
      products_supplied: JSON.stringify(['Roupas Masculinas', 'Roupas Femininas', 'Calçados', 'Acessórios'])
    },
    {
      id: 3,
      name: 'Móveis Gaúchos Ltda',
      cnpj: '33.444.555/0001-66',
      company_name: 'Móveis Gaúchos Indústria e Comércio Ltda',
      trade_name: 'Móveis Gaúchos',
      state_registration: '333.444.555.666',
      municipal_registration: '345678901',
      contact_person: 'Fernando Costa',
      email: 'pedidos@moveisgauchos.com.br',
      phone: '(51) 3234-5678',
      mobile: '(51) 99765-4321',
      website: 'https://moveisgauchos.com.br',
      address_street: 'Rua dos Móveis',
      address_number: '3200',
      address_complement: 'Fábrica 1',
      address_neighborhood: 'Distrito Industrial',
      address_city: 'Caxias do Sul',
      address_state: 'RS',
      address_zipcode: '95110-000',
      payment_terms: '60_days',
      credit_limit: 800000.00,
      current_balance: 120000.00,
      discount_percentage: 8.00,
      delivery_days: 15,
      status: 'active',
      category: 'Fabricante',
      segment: 'Móveis',
      rating: 5,
      bank_name: 'Sicredi',
      bank_agency: '3456',
      bank_account: '34567-8',
      pix_key: 'pedidos@moveisgauchos.com.br',
      notes: 'Fabricante de móveis sob medida, qualidade premium',
      contacts: JSON.stringify([
        { name: 'Luciana Rodrigues', role: 'Gerente de Vendas', phone: '(51) 99765-4322', email: 'luciana@moveisgauchos.com.br' },
        { name: 'André Souza', role: 'Coordenador de Projetos', phone: '(51) 99765-4323', email: 'andre@moveisgauchos.com.br' }
      ]),
      products_supplied: JSON.stringify(['Sofás', 'Mesas', 'Cadeiras', 'Estantes', 'Guarda-roupas'])
    },
    {
      id: 4,
      name: 'Atacadista Ferramentas MG Ltda',
      cnpj: '44.555.666/0001-77',
      company_name: 'Atacadista Ferramentas Minas Gerais Ltda',
      trade_name: 'Ferramentas MG',
      state_registration: '444.555.666.777',
      municipal_registration: '456789012',
      contact_person: 'José Carlos Almeida',
      email: 'atendimento@ferramentasmg.com.br',
      phone: '(31) 3345-6789',
      mobile: '(31) 99654-3210',
      website: 'https://ferramentasmg.com.br',
      address_street: 'Av. Contorno',
      address_number: '4500',
      address_neighborhood: 'Savassi',
      address_city: 'Belo Horizonte',
      address_state: 'MG',
      address_zipcode: '30112-000',
      payment_terms: '30_days',
      credit_limit: 200000.00,
      current_balance: 35000.00,
      discount_percentage: 4.00,
      delivery_days: 7,
      status: 'active',
      category: 'Atacadista',
      segment: 'Ferramentas',
      rating: 4,
      bank_name: 'Itaú',
      bank_agency: '4567',
      bank_account: '45678-9',
      pix_key: '44.555.666/0001-77',
      notes: 'Atacadista especializado em ferramentas e equipamentos',
      contacts: JSON.stringify([
        { name: 'Patrícia Martins', role: 'Assistente Comercial', phone: '(31) 99654-3211', email: 'patricia@ferramentasmg.com.br' },
        { name: 'Ricardo Pereira', role: 'Técnico em Ferramentas', phone: '(31) 99654-3212', email: 'ricardo@ferramentasmg.com.br' }
      ]),
      products_supplied: JSON.stringify(['Ferramentas Elétricas', 'Ferramentas Manuais', 'Equipamentos de Segurança'])
    },
    {
      id: 5,
      name: 'Importadora Global Tech Ltda',
      cnpj: '55.666.777/0001-88',
      company_name: 'Importadora Global Tech Produtos Eletrônicos Ltda',
      trade_name: 'Global Tech',
      state_registration: '555.666.777.888',
      municipal_registration: '567890123',
      contact_person: 'Michael Johnson',
      email: 'import@globaltech.com.br',
      phone: '(11) 4456-7890',
      mobile: '(11) 99543-2109',
      website: 'https://globaltech.com.br',
      address_street: 'Av. Importação',
      address_number: '1000',
      address_complement: 'Torre B',
      address_neighborhood: 'Brooklin',
      address_city: 'São Paulo',
      address_state: 'SP',
      address_zipcode: '04578-000',
      payment_terms: '60_days',
      credit_limit: 1000000.00,
      current_balance: 250000.00,
      discount_percentage: 2.00,
      delivery_days: 20,
      status: 'active',
      category: 'Importador',
      segment: 'Eletrônicos',
      rating: 5,
      bank_name: 'Bradesco',
      bank_agency: '5678',
      bank_account: '56789-0',
      pix_key: 'import@globaltech.com.br',
      notes: 'Importadora de eletrônicos, parceira exclusiva de marcas internacionais',
      contacts: JSON.stringify([
        { name: 'Fernanda Liu', role: 'Gerente de Importação', phone: '(11) 99543-2110', email: 'fernanda@globaltech.com.br' },
        { name: 'Daniel Kim', role: 'Analista de Produtos', phone: '(11) 99543-2111', email: 'daniel@globaltech.com.br' }
      ]),
      products_supplied: JSON.stringify(['Smartphones', 'Tablets', 'Acessórios Importados', 'Eletrônicos Premium'])
    },
    {
      id: 6,
      name: 'Distribuidora Automotiva SP Ltda',
      cnpj: '66.777.888/0001-99',
      company_name: 'Distribuidora Automotiva São Paulo Ltda',
      trade_name: 'Automotiva SP',
      state_registration: '666.777.888.999',
      municipal_registration: '678901234',
      contact_person: 'Roberto Machado',
      email: 'vendas@automotivasp.com.br',
      phone: '(11) 3567-8901',
      mobile: '(11) 99432-1098',
      website: 'https://automotivasp.com.br',
      address_street: 'Rua Autopeças',
      address_number: '2800',
      address_neighborhood: 'Ipiranga',
      address_city: 'São Paulo',
      address_state: 'SP',
      address_zipcode: '04267-000',
      payment_terms: '30_days',
      credit_limit: 400000.00,
      current_balance: 75000.00,
      discount_percentage: 6.00,
      delivery_days: 5,
      status: 'active',
      category: 'Distribuidor',
      segment: 'Automotivo',
      rating: 4,
      bank_name: 'Santander',
      bank_agency: '6789',
      bank_account: '67890-1',
      pix_key: '66.777.888/0001-99',
      notes: 'Distribuidora especializada em peças automotivas',
      contacts: JSON.stringify([
        { name: 'Sandra Oliveira', role: 'Coordenadora de Vendas', phone: '(11) 99432-1099', email: 'sandra@automotivasp.com.br' },
        { name: 'Marcos Ferreira', role: 'Especialista Técnico', phone: '(11) 99432-1100', email: 'marcos@automotivasp.com.br' }
      ]),
      products_supplied: JSON.stringify(['Pneus', 'Filtros', 'Óleos', 'Peças de Reposição'])
    },
    {
      id: 7,
      name: 'Cosméticos Naturais Brasil Ltda',
      cnpj: '77.888.999/0001-00',
      company_name: 'Cosméticos Naturais Brasil Indústria Ltda',
      trade_name: 'Naturais Brasil',
      state_registration: '777.888.999.000',
      municipal_registration: '789012345',
      contact_person: 'Helena Barbosa',
      email: 'comercial@naturaisbrasilCosmeticos.com.br',
      phone: '(21) 3678-9012',
      mobile: '(21) 99321-0987',
      website: 'https://naturaisbrasilCosmeticos.com.br',
      address_street: 'Estrada da Cosméticos',
      address_number: '1500',
      address_complement: 'Bloco C',
      address_neighborhood: 'Jacarepaguá',
      address_city: 'Rio de Janeiro',
      address_state: 'RJ',
      address_zipcode: '22775-000',
      payment_terms: '30_days',
      credit_limit: 150000.00,
      current_balance: 28000.00,
      discount_percentage: 7.00,
      delivery_days: 8,
      status: 'active',
      category: 'Fabricante',
      segment: 'Cosméticos',
      rating: 5,
      bank_name: 'Caixa Econômica Federal',
      bank_agency: '7890',
      bank_account: '78901-2',
      pix_key: 'comercial@naturaisbrasilCosmeticos.com.br',
      notes: 'Fabricante de cosméticos naturais, produtos orgânicos certificados',
      contacts: JSON.stringify([
        { name: 'Juliana Santos', role: 'Gerente de Produto', phone: '(21) 99321-0988', email: 'juliana@naturaisbrasilCosmeticos.com.br' },
        { name: 'Eduardo Rocha', role: 'Representante Comercial', phone: '(21) 99321-0989', email: 'eduardo@naturaisbrasilCosmeticos.com.br' }
      ]),
      products_supplied: JSON.stringify(['Cremes Hidratantes', 'Shampoos', 'Maquiagem', 'Perfumes'])
    },
    {
      id: 8,
      name: 'Alimentos Cooperativa Central Ltda',
      cnpj: '88.999.000/0001-11',
      company_name: 'Alimentos Cooperativa Central do Brasil Ltda',
      trade_name: 'Central Alimentos',
      state_registration: '888.999.000.111',
      municipal_registration: '890123456',
      contact_person: 'Antonio Silva',
      email: 'vendas@centralalimentos.com.br',
      phone: '(19) 3789-0123',
      mobile: '(19) 99210-9876',
      website: 'https://centralalimentos.com.br',
      address_street: 'Rodovia dos Alimentos',
      address_number: 'Km 45',
      address_complement: 'Distrito Agroindustrial',
      address_neighborhood: 'Zona Rural',
      address_city: 'Ribeirão Preto',
      address_state: 'SP',
      address_zipcode: '14040-000',
      payment_terms: '30_days',
      credit_limit: 350000.00,
      current_balance: 55000.00,
      discount_percentage: 4.50,
      delivery_days: 3,
      status: 'active',
      category: 'Cooperativa',
      segment: 'Alimentos',
      rating: 5,
      bank_name: 'Banco do Brasil',
      bank_agency: '8901',
      bank_account: '89012-3',
      pix_key: '88.999.000/0001-11',
      notes: 'Cooperativa de produtores rurais, produtos frescos e processados',
      contacts: JSON.stringify([
        { name: 'Marina Costa', role: 'Coordenadora Comercial', phone: '(19) 99210-9877', email: 'marina@centralalimentos.com.br' },
        { name: 'Paulo Henrique', role: 'Supervisor de Qualidade', phone: '(19) 99210-9878', email: 'paulo@centralalimentos.com.br' }
      ]),
      products_supplied: JSON.stringify(['Café', 'Açúcar', 'Cereais', 'Produtos Orgânicos'])
    }
  ]);

  console.log('✅ Suppliers seeded successfully');
  console.log('   - 8 suppliers across different categories');
  console.log('   - Distributors: 2 suppliers');
  console.log('   - Manufacturers: 3 suppliers');
  console.log('   - Importers: 1 supplier');
  console.log('   - Wholesalers: 1 supplier');
  console.log('   - Cooperatives: 1 supplier');
};